# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
# https://circleci.com/docs/2.0/browser-testing/#selenium
# syntax version
version: 2
# Jobs description
jobs:
  # Name of jobs
  QaseIO tests:
    # Check https://circleci.com/docs/2.0/docker-image-tags.json for the list of all docker images. What will be installed within docker container/
    docker:
      - image: circleci/openjdk:11.0.8-jdk-browsers
    steps:
      # From the linked remote repository please copy the code - CLONE GIT REPO
      - checkout
      # Start. Check already installed somewhere dependencies, if they exist then they download from if not the search in the web and download
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      # End
      # Console commands
      - run:
          name: Running tests
          command: mvn clean test
      - run:
          name: Generate allure report
          command: mvn allure:report
          when: always
      - store_test_results:
          path: target/surefire-reports/junitreports
          when: always
      - store_artifacts:
          path: target/site/allure-maven-plugin/
workflows:
  version: 2
  commit:
    jobs:
      - QaseIO tests
  periodical:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - QaseIO tests